language: php

php:
  - '7.0'
  - '7.1'

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - cp .env.travis .env
  - composer update --prefer-source $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit